# Generated by Django 4.2.4 on 2023-08-10 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider_name', models.CharField(max_length=100)),
                ('Emarat', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=100)),
                ('Guest', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Note', models.TextField(blank=True, max_length=500)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('phone', models.CharField(max_length=11)),
                ('Provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('Date', 'Time'), name='Date and Time'),
        ),
    ]
